# Sync all the image tags including latest
europe-docker.pkg.dev/gitpod-artifacts/docker-dev:
  images:
    workspace-base:
    workspace-c:
    workspace-clojure:
    workspace-full:
    workspace-go:
    workspace-node:
    workspace-node-lts:
    workspace-python:
    workspace-ruby-2:
    workspace-ruby:
    workspace-rust:
