image:
  file: .gitpod.Dockerfile

ports:
  - port: 5000
    onOpen: ignore

tasks:
  - name: start up buildkitd
    command: |
      cd dazzle-rewrite
      sudo /usr/bin/buildkitd --debug  --config ./buildkitd.toml --group gitpod
  - name: server a local docker registry
    command: |
      mkdir -p /workspace/registry
      docker run -p 5000:5000 --name registry --rm -v /workspace/registry:/var/lib/registry registry:2
    openMode: split-right
  - name: get latest version of dazzle, build and test images
    before: |
      curl -sSL https://github.com/gitpod-io/dazzle/releases/download/v0.1.6/dazzle_0.1.6_Linux_x86_64.tar.gz | sudo tar -xvz -C /usr/local/bin
    command: |
      cd dazzle-rewrite
      gp await-port 5000
      REPO=localhost:5000/dazzle
      echo "First, build chunks without hashes 'time sudo $(which dazzle) build $REPO -v --chunked-without-hash'"
      echo "Second, build again 'time sudo $(which dazzle) build $REPO -v'"
      echo "Third, create combinations of chunks 'time sudo $(which dazzle) combine $REPO --all -v'"
      echo "To list chunk images, which can be tested individually with docker 'sudo $(which dazzle) project image-name $REPO'"
      echo "To list hashes for chunked images 'sudo $(which dazzle) project hash $REPO'"
      echo "To print the combined image maniest 'sudo $(which dazzle) project manifest $REPO'"
      echo "Image content cached in this workspace...'du -shc /workspace/registry/*'"
    openMode: tab-after
  - name: watch file system
    command: watch -n 5 df -H
  - name: watch buildkit disk usage
    command: watch -n 5 'buildctl du | grep "Total"'
    openMode: split-right

vscode:
  extensions:
    - ms-azuretools.vscode-docker

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true
