name: Build on Push
on: [push]

env:
  REGISTRY: ghcr.io
  OS_BASE: focal

jobs:
  build-deps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU dependency
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/buildpack-deps
      # https://stackoverflow.com/questions/58033366/how-to-get-the-current-branch-within-github-actions
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Extract lowercase repository name
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
        id: string
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: buildpack-deps
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=${{ steps.meta.outputs.tags }}-cache-${{ env.OS_BASE }}
          cache-to: type=registry,ref=${{ steps.meta.outputs.tags }}-cache-${{ env.OS_BASE }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            BASE_IMAGE=${{ env.REGISTRY }}/${{ steps.string.outputs.lowercase }}
            BASE_TAG=${{ steps.extract_branch.outputs.branch }}

  build-base:
    runs-on: ubuntu-latest
    # needs: build-deps
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU dependency
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/base
      # https://stackoverflow.com/questions/58033366/how-to-get-the-current-branch-within-github-actions
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Extract lowercase repository name
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
        id: string
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: base
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=${{ steps.meta.outputs.tags }}-cache-${{ env.OS_BASE }}
          cache-to: type=registry,ref=${{ steps.meta.outputs.tags }}-cache-${{ env.OS_BASE }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            BASE_IMAGE=docker.io
            BASE_TAG=focal

  build-full:
    needs: build-base
    strategy:
      matrix:
        include:
         - node: "ubuntu-latest"
           tag: "amd64"
         - node: "ARM64"
           tag: "arm64"
    runs-on: ${{ matrix.node }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Set up QEMU dependency
      #   uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/full
      # https://stackoverflow.com/questions/58033366/how-to-get-the-current-branch-within-github-actions
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Extract lowercase repository name
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
        id: string
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: full
          push: true
          tags: ${{ steps.meta.outputs.tags }}-${{ matrix.tag }}
          cache-from: type=registry,ref=${{ steps.meta.outputs.tags }}-cache-${{ env.OS_BASE }}-${{ matrix.tag }}
          cache-to: type=registry,ref=${{ steps.meta.outputs.tags }}-cache-${{ env.OS_BASE }}-${{ matrix.tag }}
          labels: ${{ steps.meta.outputs.labels }}
          # platforms: linux/amd64,linux/arm64
          build-args: |
            BASE_IMAGE=${{ env.REGISTRY }}/${{ steps.string.outputs.lowercase }}
            BASE_TAG=${{ steps.extract_branch.outputs.branch }}

  build-full-manifest:
    needs: build-full
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU dependency
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/full
      # https://stackoverflow.com/questions/58033366/how-to-get-the-current-branch-within-github-actions
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Extract lowercase repository name
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
        id: string
      - name: Create manifest
        shell: bash
        run: |
          docker manifest create ${{ env.REGISTRY }}/${{ steps.string.outputs.lowercase }}/full:${{ steps.extract_branch.outputs.branch }} --amend ${{ env.REGISTRY }}/${{ steps.string.outputs.lowercase }}/full:${{ steps.extract_branch.outputs.branch }}-arm64 --amend ${{ env.REGISTRY }}/${{ steps.string.outputs.lowercase }}/full:${{ steps.extract_branch.outputs.branch }}-amd64
          docker manifest push ${{ env.REGISTRY }}/${{ steps.string.outputs.lowercase }}/full:${{ steps.extract_branch.outputs.branch }}

  build-matrix:
    needs: build-full-manifest
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        # node: [ dart, dotnet-lts, flutter, full-vnc, mdbook, mongodb, mysql, postgres, wasm ]
        node: [ full-vnc ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU dependency
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/full
      # https://stackoverflow.com/questions/58033366/how-to-get-the-current-branch-within-github-actions
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Extract lowercase repository name
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
        id: string
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.node }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=${{ steps.meta.outputs.tags }}-cache-${{ env.OS_BASE }}
          cache-to: type=registry,ref=${{ steps.meta.outputs.tags }}-cache-${{ env.OS_BASE }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            BASE_IMAGE=${{ env.REGISTRY }}/${{ steps.string.outputs.lowercase }}
            BASE_TAG=${{ steps.extract_branch.outputs.branch }}
          
  build-matrix-vnc:
    needs: build-matrix
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        # node: [ dotnet-lts-vnc, dotnet-vnc, flutter, gecko ]
        node: [ ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU dependency
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/full
      # https://stackoverflow.com/questions/58033366/how-to-get-the-current-branch-within-github-actions
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Extract lowercase repository name
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
        id: string
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.node }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=${{ steps.meta.outputs.tags }}-cache-${{ env.OS_BASE }}
          cache-to: type=registry,ref=${{ steps.meta.outputs.tags }}-cache-${{ env.OS_BASE }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            BASE_IMAGE=${{ env.REGISTRY }}/${{ steps.string.outputs.lowercase }}
            BASE_TAG=${{ steps.extract_branch.outputs.branch }}
          
  build-gitpod-dev-image:
    strategy:
      matrix:
        include:
         - node: "ubuntu-latest"
           tag: "amd64"
         - node: "ARM64"
           tag: "arm64"
    runs-on: ${{ matrix.node }}
    needs: build-full-manifest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Set up QEMU dependency
      #   uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/gitpod-dev
      # https://stackoverflow.com/questions/58033366/how-to-get-the-current-branch-within-github-actions
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Extract lowercase repository name
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
        id: string
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: gitpod-dev-image
          push: true
          tags: ${{ steps.meta.outputs.tags }}-${{ matrix.tag }}
          cache-from: type=registry,ref=${{ steps.meta.outputs.tags }}-cache-${{ env.OS_BASE }}-${{ matrix.tag }}
          cache-to: type=registry,ref=${{ steps.meta.outputs.tags }}-cache-${{ env.OS_BASE }}-${{ matrix.tag }}
          labels: ${{ steps.meta.outputs.labels }}
          # platforms: linux/amd64,linux/arm64
          build-args: |
            BASE_IMAGE=${{ env.REGISTRY }}/${{ steps.string.outputs.lowercase }}
            BASE_TAG=${{ steps.extract_branch.outputs.branch }}

  build-gitpod-dev-image-manifest:
    needs: build-full
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU dependency
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/full
      # https://stackoverflow.com/questions/58033366/how-to-get-the-current-branch-within-github-actions
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Extract lowercase repository name
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
        id: string
      - name: Create manifest
        shell: bash
        run: |
          docker manifest create ${{ env.REGISTRY }}/${{ steps.string.outputs.lowercase }}/gitpod-dev-image:${{ steps.extract_branch.outputs.branch }} --amend ${{ env.REGISTRY }}/${{ steps.string.outputs.lowercase }}/full:${{ steps.extract_branch.outputs.branch }}-arm64 --amend ${{ env.REGISTRY }}/${{ steps.string.outputs.lowercase }}/full:${{ steps.extract_branch.outputs.branch }}-amd64
          docker manifest push ${{ env.REGISTRY }}/${{ steps.string.outputs.lowercase }}/gitpod-dev-image:${{ steps.extract_branch.outputs.branch }}
