name: Build from Pull Request
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: 📥 Checkout workspace-images
        uses: actions/checkout@v2
        with:
          repository: gitpod-io/workspace-images

      - name: 🕰️ Create timestamp tag
        id: create-timestamp-tag
        run: |
          echo "::set-output name=TIMESTAMP_TAG::$(date '+%Y-%m-%d-%H-%M-%S')"
          echo  TIMESTAMP_TAG=$(date '+%Y-%m-%d-%H-%M-%S') >> $GITHUB_ENV

      - name: 🤓 test step
        run: |
          echo Image_tags ${{ steps.create-timestamp-tag.TIMESTAMP_TAG }}
          echo envimgtag ${{ TIMESTAMP_TAG }}
